name: Build and Push to Docker Hub

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get latest Terraform version
      id: get-terraform-version
      # echo ::set-output name=terraform_version::$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | jq -r .tag_name)
      run: |
        set -e

        # Function to get all available Terraform versions
        available_versions=$(curl -s https://releases.hashicorp.com/terraform/ | grep -oP 'terraform_[^<]+' | cut -d '_' -f 2 | sort -V)

        # Filter out alpha and beta versions
        filtered_versions=$(echo "$available_versions" | grep -v -E 'alpha|beta|rc')

        # Get the most recent stable version
        latest_version=$(echo "$filtered_versions" | tail -n 1)

        echo $latest_version

        echo "terraform-version=$latest_version" >> "$GITHUB_OUTPUT"

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: |
          TERRAFORM_VERSION=${{ steps.get-terraform-version.outputs.terraform-version }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get-terraform-version.outputs.terraform-version }}
          ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
